//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace wpf_login
{
    using System;
    using System.Collections.Generic;
    
    public partial class logsData
    {
        public int id_session { get; set; }
        public Nullable<int> code_person { get; set; }
        public Nullable<System.DateTime> date_session { get; set; }
        public string time { get; set; }
    
        public virtual person person { get; set; }
    }
}
